version: '3.6'

services:
  sintrop-app:
    container_name: AGRO-CHAIN
    command: ["sleep", "infinity"]
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8545:8545
      - 5001:5001
      - 8080:8080
    networks: 
      - app-tunnel
    volumes: 
      - ./:/app
networks: 
  app-tunnel:
    driver: bridge